name: Upload Card


on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload card
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/heatger-card.js application/javascript
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
